package com.example.mybatis.mybatisdemo.dao;

import com.example.mybatis.mybatisdemo.model.DepartmentDO;
import com.example.mybatis.mybatisdemo.model.DepartmentDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    long countByExample(DepartmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int deleteByExample(DepartmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int insert(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int insertSelective(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    List<DepartmentDO> selectByExample(DepartmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    DepartmentDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") DepartmentDO record, @Param("example") DepartmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int updateByExample(@Param("record") DepartmentDO record, @Param("example") DepartmentDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int updateByPrimaryKeySelective(DepartmentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int updateByPrimaryKey(DepartmentDO record);
}