package com.example.mybatis.mybatisdemo.dao;

import com.example.mybatis.mybatisdemo.model.EmployeeDO;
import com.example.mybatis.mybatisdemo.model.EmployeeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    long countByExample(EmployeeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int deleteByExample(EmployeeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int insert(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int insertSelective(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    List<EmployeeDO> selectByExample(EmployeeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    EmployeeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") EmployeeDO record, @Param("example") EmployeeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int updateByExample(@Param("record") EmployeeDO record, @Param("example") EmployeeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int updateByPrimaryKeySelective(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Thu Jul 30 16:07:57 CST 2020
     */
    int updateByPrimaryKey(EmployeeDO record);
}